version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: taskmaster-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Hari@8328
      MYSQL_DATABASE: taskmaster
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmaster-backend
    restart: always
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/taskmaster?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hari@8328
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: taskmaster-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  uploads_data:
